name: ca4016_application_domains
channels:
  - conda-forge

dependencies:
  - jupyterlab
  - python=3.8
  - scikit-learn=0.23.2
  - pandas
  - pip
  - jupyterlab-git
  - jupyter-execute-time
  - pip:
    - pycaret
    - yellowbrick
